### ISSUE TITLE
IDE error when using macro fields on anon struct fields

### ISSUE THREAD

**Issue by pierrec** [c3lang/c3intellij#2]
```
macro @(r, #x, #y)
{
  Rectangle rc = { .#x = r.#x };
}
```

the .#x is highlighted and gives an error in the IDE.

> C3TokenType.IDENT expected got '#x'

**Comment by lerno** [comment]
The funny thing is that I didn't even plan for this to work 😆 I'll have a look at it

**Comment by pierrec** [comment]
Works for me in 0.0.8. Thanks :)!
