### ISSUE TITLE
nextcase default

### ISSUE THREAD

**Issue by pierrec** [c3lang/c3intellij#4]
A `nextcase default` is not recognized as of v0.0.11.

**Comment by lerno** [comment]
0.0.12 is uploaded.

**Comment by lerno** [comment]
See if this works in 0.0.12

**Comment by pierrec** [comment]
Thanks for the quick turnaround! Fixed.

**Comment by lerno** [comment]
I was seeing if I needed some more updates, that's why I had put off pushing 0.0.12
